
CREATE TABLE IF NOT EXISTS TEAM (
  TEAM_ID INT UNSIGNED AUTO_INCREMENT,
  TEAM_NAME VARCHAR(225) NOT NULL,
  PLAYER INT NOT NULL,
  GENDER VARCHAR(1) NOT NULL,
  CREATE_DATE INT NOT NULL,
  STATUS INT NOT NULL,
  PROJECT VARCHAR(225) NOT NULL,
  H_UNIFORM VARCHAR(3) ,
  A_UNIFORM VARCHAR(3),
PRIMARY KEY (TEAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


INSERT INTO team (TEAM_NAME, PLAYER, GENDER, CREATE_DATE, STATUS, PROJECT, H_UNIFORM, A_UNIFORM) VALUES
  ('team32', '5', 'M', '22188', '1', 'BASKETBALL', 'WRT', 'BLK');